{
 "title": "Dashboard-Prefill-p50/p99",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "E2E p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, model_name) (\n    rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "E2E p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, model_name) (\n    rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prefill50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.50,\n  sum by (le, model_name) (\n    rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "prefill p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le, model_name) (\n    rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decode p50",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.50,\n    sum by (le, model_name) (\n      rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])\n    )\n  )\n)\n-\n(\n  histogram_quantile(\n    0.50,\n    sum by (le, model_name) (\n      rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Decode p99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  histogram_quantile(\n    0.99,\n    sum by (le, model_name) (\n      rate(vllm:e2e_request_latency_seconds_bucket[$__rate_interval])\n    )\n  )\n)\n-\n(\n  histogram_quantile(\n    0.99,\n    sum by (le, model_name) (\n      rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])\n    )\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}